version: '2'

services:
  strongswan:
    image: philplckthun/strongswan
    container_name: strongswan
    restart: "always"
    volumes:
      - "./ipsec.conf:/etc/ipsec.conf"
      - "./ipsec.secrets:/etc/ipsec.secrets"
    environment:
      - VPN_USER=yu
      - VPN_PASSWORD=yu
      - VPN_PSK=123
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    privileged: true

  dante:
    image: wernight/dante
    container_name: dante
    restart: "always"
    network_mode: "bridge"
    ports:
      - "9999:1080"
  privoxy:
    image: vimagick/privoxy
    container_name: privoxy
    network_mode: host
    volumes:
      - "./config:/etc/privoxy/config"

