version: '2'

services:
  strongswan:
    image: philplckthun/strongswan
    container_name: strongswan
    build: .
    volumes:
      - "./ipsec.conf:/etc/ipsec.conf"
      - "./ipsec.secrets:/etc/ipsec.secrets"
      - ".:/app"
    networks:
      - vpn
    environment:
      - PATH=$PATH:/bin/versions/node/v14.21.3/bin
      - VPN_USER=yu
      - VPN_PASSWORD=yu
      - VPN_PSK=123
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
      - "10000:10000/tcp"
      - "9999:1080"
    privileged: true
    restart: "always"
  dante:
    image: wernight/dante
    depends_on:
      - strongswan
    network_mode: "container:strongswan"
    privileged: true
    restart: "always"

  privoxy:
    image: vimagick/privoxy
    container_name: privoxy
    depends_on:
      - dante
    networks:
      - vpn
    ports:
      - "9998:9998"
    volumes:
      - "./config:/etc/privoxy/config"
    restart: "always"

  # nginx:
  #   restart: "always"
  #   image: nginx
  #   container_name: nginx
  #   network_mode: host
  #   volumes:
  #     - "./certs:/certs"
  #     - "./conf.d/default.conf:/etc/nginx/conf.d/default.conf"
  #     - "/root/richoleyu.github.io/public:/html"
networks:
  vpn:
