version: '2'

services:
  strongswan:
    image: philplckthun/strongswan
    container_name: strongswan
    volumes:
      - "./ipsec.conf:/etc/ipsec.conf"
      - "./ipsec.secrets:/etc/ipsec.secrets"
    environment:
      - VPN_USER=yu
      - VPN_PASSWORD=yu
      - VPN_PSK=123
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
      - "1701:1701/udp"
    privileged: true

  dante:
    image: wernight/dante
    container_name: dante
    network_mode: "bridge"
    networks:
      - vpn
    ports:
      - "9999:1080"
      - "9998:9998"

  privoxy:
    image: vimagick/privoxy
    container_name: privoxy
    network_mode: 'container:dante'
    volumes:
      - "./config:/etc/privoxy/config"
  
  vpn_whiteList:
    container_name: vpn_whitelist
    build: .
    privileged: true
    ports:
      - "10000:10000"
  
networks:
  vpn: